# Generated by Django 4.2.5 on 2023-09-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_lab',
            name='user',
        ),
    ]
