# Generated by Django 4.2.4 on 2023-09-17 15:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0002_remove_schedule_lab_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 17, 21, 0)),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 17, 9, 0)),
        ),
        migrations.AddField(
            model_name='schedule_lab',
            name='status',
            field=models.CharField(choices=[(1, 'Pendente'), (2, 'Cancelado'), (3, 'Confirmado')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule_lab',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
