# Generated by Django 4.2.5 on 2023-09-21 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_laboratory_closing_time_laboratory_opening_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 21, 21, 0)),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 21, 9, 0)),
        ),
    ]
