# Generated by Django 4.2.5 on 2023-09-26 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_laboratory_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 26, 21, 0)),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 26, 9, 0)),
        ),
    ]
